-- Users table
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  firstName VARCHAR(100),
  lastName VARCHAR(100),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Loans table
CREATE TABLE IF NOT EXISTS loans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  loanAmount DECIMAL(15, 2) NOT NULL,
  propertyAddress VARCHAR(255) NOT NULL,
  status ENUM('PENDING_VERIFICATION', 'VERIFIED', 'VERIFICATION_FAILED', 'PENDING_ELIGIBILITY', 'APPROVED', 'REJECTED') DEFAULT 'PENDING_VERIFICATION',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

-- Documents table
CREATE TABLE IF NOT EXISTS documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  loanId INT NOT NULL,
  documentType VARCHAR(100),
  documentPath VARCHAR(255),
  verificationStatus ENUM('PENDING', 'VERIFIED', 'REJECTED') DEFAULT 'PENDING',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (loanId) REFERENCES loans(id) ON DELETE CASCADE
);

-- Audit log table
CREATE TABLE IF NOT EXISTS audit_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  loanId INT,
  userId INT,
  action VARCHAR(255) NOT NULL,
  details JSON,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (loanId) REFERENCES loans(id) ON DELETE SET NULL,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE SET NULL
);

-- Create indexes
CREATE INDEX idx_loans_userId ON loans(userId);
CREATE INDEX idx_loans_status ON loans(status);
CREATE INDEX idx_documents_loanId ON documents(loanId);
CREATE INDEX idx_audit_log_loanId ON audit_log(loanId);
CREATE INDEX idx_audit_log_userId ON audit_log(userId);
